### ISSUE TITLE
Results not as expected

### ISSUE THREAD

**Issue by feihugis** [fitodic/centerline#13]
Thanks for your library! 

I'm trying to use this library to get the centerline of the roads (polygon). However, as the following figure show, besides the centerline, there are many short lines along the centerline. Is there any way to remove these short lines?

<img width="1421" alt="screen shot 2018-01-09 at 11 55 24 pm" src="https://user-images.githubusercontent.com/5057740/34756413-ab80cb7c-f598-11e7-9f78-3c64648ce119.png">

**Comment by fitodic** [comment]
From what I can see, this polygon data set is very detailed. Nevertheless, there are several options you can look into:

1. Modify the border density parameter (by default it is set to 0.5 meters)
2. Simplify the polygon data set (e.g. QGIS)
3. Simplify the centerline data set (e.g. QGIS)

**Comment by feihugis** [comment]
@fitodic Thanks for your suggestion! The results got much better by simplifying the polygon data using Shapely simplify function.

**Comment by fitodic** [comment]
Glad I could help 🙂

**Comment by fitodic** [comment]
@ahmathlete Hi :) 
As to option 1, there is a [parameter](https://centerline.readthedocs.io/en/latest/_modules/centerline/geometry.html#Centerline) that increases or decreases the density of the input geometry:

```python
>>> from shapely.geometry import Polygon
>>> from centerline.geometry import Centerline

>>> polygon = Polygon([[0, 0], [0, 4], [4, 4], [4, 0]])
>>> attributes = {"id": 1, "name": "polygon", "valid": True}

>>> centerline = Centerline(polygon, interpolation_distance=1.5 **attributes)
```
You can also pass the same value to the [command line](https://github.com/fitodic/centerline/blob/master/src/centerline/converters.py#L38) script.

As to option 3, you create the centerline dataset (e.g. using the `create_centerline` CLI command), open the centerline dataset in [QGIS](https://www.qgis.org/en/site/) and manually delete the nodes that stick out.

**Comment by ahmathlete** [comment]
@fitodic Hello:) 

Thanks for the helpful tips. Since am doing programmatically for large set of data, I will leave these steps in case someone  will need it : 
1. Chaikin's corner-cutting algorithm with refinements degree of X0
2. Shapely simplify function with a tolerance of X1
3. Centerline function with interpolation distance X2

X0, X1, X2 values depend mainly on details of the work and desired results.

**Comment by fitodic** [comment]
@ahmathlete Thanks for clarifying 🙂 
If you're willing, you can always update the [documentation](https://github.com/fitodic/centerline/blob/master/docs/chapters/faq.rst#the-level-of-detail-is-too-highthe-geometry-is-too-complex) with this info. I know it depends on the dataset, but it never hurts to supply an example.
