### ISSUE TITLE
Ubuntu 16.04 install issues

### ISSUE THREAD

**Issue by headdab** [fitodic/centerline#22]
I've tried many things and have scanned the the web and stack-exchange, and I still can't install this.  On ubuntu 16.04, in my most recent attempt, I did the following:

sudo apt install python-gdal
python3 -m venv CL
. CL/bin/activate
pip install -U pip setuptools wheel
pip install GDAL==2.2.2
pip install centerline

The last step fails as follows liekly because its trying to install/build GDAL>-2.3.3.
Is there an earlier version of centerline that I can install with GDAL==2.2.2?

**Comment by fitodic** [comment]
What version of `GDAL` do you have installed locally? Try running the `gdalinfo --version` in your terminal.

I haven't used Ubuntu in quite some time, but I remember Ubuntu having pretty old versions of packages. I had to enable the [ubuntugis-unstable](https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable) repository to install a newer version of `GDAL`. Either that, or manually build it.

If you want to install a version of `centerline` that still supports `GDAL==2.2.2`, you could try `centerline==0.5`
