### ISSUE TITLE
QhullError: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 4

### ISSUE THREAD

**Issue by snarb** [fitodic/centerline#24]
Using  poligon with points: 
> [(107, 189),
>  (106, 190),
>  (100, 190),
>  (99, 191),
>  (95, 191),
>  (94, 192),
>  (92, 192),
>  (91, 193),
>  (90, 193),
>  (89, 194),
>  (88, 194),
>  (87, 195),
>  (86, 195),
>  (85, 196),
>  (84, 196),
>  (82, 198),
>  (82, 203),
>  (86, 207),
>  (87, 207),
>  (90, 210),
>  (91, 210),
>  (92, 211),
>  (94, 211),
>  (95, 212),
>  (98, 212),
>  (99, 213),
>  (101, 213),
>  (102, 214),
>  (105, 214),
>  (106, 215),
>  (108, 215),
>  (109, 216),
>  (111, 216),
>  (112, 217),
>  (114, 217),
>  (115, 218),
>  (117, 218),
>  (118, 219),
>  (120, 219),
>  (121, 220),
>  (126, 220),
>  (127, 221),
>  (133, 221),
>  (134, 222),
>  (136, 222),
>  (137, 223),
>  (138, 223),
>  (139, 224),
>  (139, 227),
>  (137, 229),
>  (137, 230),
>  (136, 231),
>  (135, 231),
>  (133, 233),
>  (132, 233),
>  (130, 235),
>  (129, 235),
>  (126, 238),
>  (125, 238),
>  (124, 239),
>  (123, 239),
>  (122, 240),
>  (121, 240),
>  (120, 241),
>  (119, 241),
>  (118, 242),
>  (116, 242),
>  (115, 243),
>  (114, 243),
>  (113, 244),
>  (112, 244),
>  (110, 246),
>  (109, 246),
>  (108, 247),
>  (107, 247),
>  (106, 248),
>  (105, 248),
>  (104, 249),
>  (102, 249),
>  (101, 250),
>  (99, 250),
>  (98, 251),
>  (97, 251),
>  (96, 252),
>  (94, 252),
>  (92, 254),
>  (91, 254),
>  (90, 255),
>  (89, 255),
>  (88, 256),
>  (87, 256),
>  (86, 257),
>  (85, 257),
>  (84, 258),
>  (83, 258),
>  (82, 259),
>  (80, 259),
>  (79, 260),
>  (78, 260),
>  (70, 268),
>  (70, 269),
>  (69, 270),
>  (69, 272),
>  (68, 273),
>  (68, 276),
>  (71, 279),
>  (73, 279),
>  (74, 280),
>  (83, 280),
>  (84, 279),
>  (90, 279),
>  (91, 278),
>  (94, 278),
>  (95, 277),
>  (97, 277),
>  (98, 276),
>  (99, 276),
>  (100, 275),
>  (101, 275),
>  (103, 273),
>  (105, 273),
>  (106, 272),
>  (108, 272),
>  (109, 271),
>  (111, 271),
>  (112, 270),
>  (113, 270),
>  (114, 269),
>  (115, 269),
>  (116, 268),
>  (117, 268),
>  (120, 265),
>  (121, 265),
>  (122, 264),
>  (124, 264),
>  (125, 263),
>  (126, 263),
>  (127, 262),
>  (128, 262),
>  (129, 261),
>  (130, 261),
>  (132, 259),
>  (133, 259),
>  (135, 257),
>  (136, 257),
>  (137, 256),
>  (138, 256),
>  (139, 255),
>  (141, 255),
>  (142, 254),
>  (143, 254),
>  (145, 252),
>  (146, 252),
>  (149, 249),
>  (150, 249),
>  (153, 246),
>  (154, 246),
>  (158, 242),
>  (158, 241),
>  (164, 235),
>  (164, 234),
>  (165, 233),
>  (165, 232),
>  (166, 231),
>  (166, 230),
>  (167, 229),
>  (167, 227),
>  (168, 226),
>  (168, 223),
>  (169, 222),
>  (169, 220),
>  (170, 219),
>  (170, 212),
>  (169, 211),
>  (169, 210),
>  (168, 209),
>  (168, 208),
>  (167, 207),
>  (167, 206),
>  (162, 201),
>  (161, 201),
>  (159, 199),
>  (158, 199),
>  (157, 198),
>  (155, 198),
>  (154, 197),
>  (153, 197),
>  (151, 195),
>  (150, 195),
>  (149, 194),
>  (147, 194),
>  (146, 193),
>  (144, 193),
>  (143, 192),
>  (139, 192),
>  (138, 191),
>  (132, 191),
>  (131, 190),
>  (122, 190),
>  (121, 189)]
![Screenshot from 2019-10-08 09-45-35](https://user-images.githubusercontent.com/4518007/66401459-dd3f2480-e9eb-11e9-8308-be39a68aa2bf.png)

> 
> polygon = Polygon(pts)
> attributes = {"id": 1, "name": "polygon", "valid": True}
> centerline = Centerline(polygon, **attributes)
> 

I got:
> QhullError: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 4

**Comment by fitodic** [comment]
@snarb Have you tried modifying the [`interpolation_distance`](https://centerline.readthedocs.io/en/latest/modules/centerline.html#centerline.geometry.Centerline) parameter? 

This error has occurred before and is documented in the [_Frequently Asked Questions_](https://centerline.readthedocs.io/en/latest/chapters/faq.html#id1) section, but a more user-friendly error message is definitely needed to avoid misunderstandings.

**Comment by totoroyun** [comment]
Have you solved this problem?

**Comment by fitodic** [comment]
Hi,
sorry for the delay, I've been quite busy lately to investigate this more thoroughly, but pull requests are always welcome.

Essentially, this is a well-known and [documented](https://centerline.readthedocs.io/en/latest/chapters/faq.html#id1) edge-case that depends on the user's input, i.e. provided `interpolation_distance`. Adjusting this parameter should allow you to construct the centerline.

All that remains is to provide a more "user-friendly" error message.

**Comment by totoroyun** [comment]
Thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Filip Todic"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 下午4:17
收件人:&nbsp;"fitodic/centerline"<centerline@noreply.github.com&gt;;
抄送:&nbsp;"2546036949"<2546036949@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fitodic/centerline] QhullError: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 4 (#24)




Hi,
 sorry for the delay, I've been quite busy lately to investigate this more thoroughly, but pull requests are always welcome.
 
Essentially, this is a well-known and documented edge-case that depends on the user's input, i.e. provided interpolation_distance. Adjusting this parameter should allow you to construct the centerline.
 
All that remains is to provide a more "user-friendly" error message.

**Comment by fitodic** [comment]
@snarb I'm sorry, but I wasn't able to reproduce this issue. A test that tries to reproduce this issue was added in 4aefa54, and the [centerline object is created successfully](https://travis-ci.org/fitodic/centerline/builds/631826450).

Could you please check the input data?

**Comment by Ptero793** [comment]
thank you!
