### ISSUE TITLE
Initial simplex is flat (facet 1 is coplanar with the interior point)

### ISSUE THREAD

**Issue by eLvErDe** [fitodic/centerline#27]
Hello,

I cannot compute centerline using your module and attached polygon.
Any help would be greatly appreciated !

Regards,

**Comment by eLvErDe** [comment]
[poly.json.txt](https://github.com/fitodic/centerline/files/4117683/poly.json.txt)

**Comment by fitodic** [comment]
Hi,
have you tried adjusting the border density to a low value (e.g. 0.00001)? 

`$ create_centerlines input.shp output.geojson 0.00001`

As [documented](https://centerline.readthedocs.io/en/latest/chapters/faq.html#id1), the data can be stored in a format that uses degrees, whereas the `Centerline` class uses a metric system.
