### ISSUE TITLE
what is centerline instance ?

### ISSUE THREAD

**Issue by ob-chen** [fitodic/centerline#3]
Hi, I'm trying to use this code to find Centerline inside a polygon.  I got a  TypeError.
`TypeError: unbound method createCenterline() must be called with Centerline instance as first argument (got ndarray instance instead)`

I gave it a wkt polygon string. However, I don't know what should Centerline instance look like.
Could anyone give me some example? I didnt find the documents.
Many thanks.

**------update------**
I created self by  Centerline() and I got this: `'list' object has no attribute 'envelope'`

**Comment by fitodic** [comment]
Hi,

there is an example in the [shp2centerline](https://github.com/fitodic/centerline/blob/master/bin/shp2centerline#L36) script on how to create `Centerline` objects. As you can see, it uses shapely's [shape](http://toblerity.org/shapely/shapely.geometry.html#shapely.geometry.shape) function to create the geometry object. 

There are certainly other ways of achieving the same thing. :slightly_smiling_face: Have you tried creating a [Polygon](http://toblerity.org/shapely/manual.html#Polygon) object from the WKT data?

**Comment by ob-chen** [comment]
Hi, 
Thank you for getting back to me.
It works for me when I use WKT Polygon. However, I got `QhullError` when I run voronoi .
