### ISSUE TITLE
shapely 2.0.0 issue

### ISSUE THREAD

**Issue by raybellwaves** [fitodic/centerline#35]
```
    centerline_geom = centerline.geometry.Centerline(
TypeError: MultiLineString.__new__() got an unexpected keyword argument 'interpolation_distance'
```

if I have time i'll try to come back to this and give a minimal example

see also:
 - https://github.com/fitodic/centerline/pull/30
 - https://github.com/fitodic/centerline/issues/29

**Comment by fitodic** [comment]
[Version 1.0](https://pypi.org/project/centerline/1.0.0/) was released so you can give it a go

**Comment by raybellwaves** [comment]
Thank you very much!
