### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument "XXX"

### ISSUE THREAD

**Issue by gladcolor** [fitodic/centerline#36]
When testing using `centerline = Centerline(polygon, **attributes)` or command line, 
Reports "TypeError: __new__() got an unexpected keyword argument 'XXX,' "XXX" is the first attribute name.

I have tested on several machines; the results were the same.

**Comment by phamkhactu** [comment]
@gladcolor I have the same proplem with shapely 2.0. Have you solve it?

**Comment by fitodic** [comment]
Similar to #29 and #35. Unfortunately, I haven't found the time to address it properly. For now, you can try using `shapely<2.0` so it works as it did before.

**Comment by fitodic** [comment]
@gladcolor @phamkhactu [Version 1.0](https://pypi.org/project/centerline/1.0.0/) was released so you can give it a go

**Comment by phamkhactu** [comment]
> @gladcolor @phamkhactu [Version 1.0](https://pypi.org/project/centerline/1.0.0/) was released so you can give it a go

hi @fitodic I have ever try installed, but can not find the version 
```
ERROR: Could not find a version that satisfies the requirement centerline==1.0.0 (from versions: 0.1, 0.2, 0.2.1, 0.3, 0.4, 0.4.1, 0.4.2, 0.5, 0.5.2, 0.6.0, 0.6.3, 0.6.4)
ERROR: No matching distribution found for centerline==1.0.0
```
