### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by mperlet** [fitodic/centerline#38]
Hey,
thanks for your work. 

The current version 1.0.0 cannot be installed with python 3.7. 
```
pip install git+https://github.com/fitodic/centerline@1.0.0

ERROR: Package 'centerline' requires a different Python: 3.7.16 not in '>=3.8'
```
Python 3.7 is listed here: https://github.com/fitodic/centerline/blob/master/setup.cfg#L22 and 
the constraint is defined here: https://github.com/fitodic/centerline/blob/master/setup.cfg#L31.

Is Python 3.8 really necessary, or can we also enable the other versions? Otherwise we should update the classifiers. 

Thank you
Mathias

**Comment by fitodic** [comment]
You're right, there's no requirement for using Python 3.8+ so I dropped it to Python 3.7+ and updated the metadata (which I always forget to do). Thanks for noticing :+1: 

I released 1.0.1 so it should be available on PyPI shortly.
