### ISSUE TITLE
Cite!

### ISSUE THREAD

**Issue by mvsc1** [fitodic/centerline#43]
We would like to cite centerline in one of our papers. Can you please add a CITATION.cff file, zenodo id? We may cite this repository as (Todić, 2023)? Thank you!

**Comment by fitodic** [comment]
Hi, sure. I added a [CITATION.cff](https://github.com/fitodic/centerline/blob/master/CITATION.cff) file to the `master` branch. Is that enough?

**Comment by mvsc1** [comment]
Perfect! Thank you so much!
